on: 
  push:
    branches:
      - main
name: merge master
jobs:
  firstJob:
      name: Echo GITHUB_HEAD_REF
      runs-on: ubuntu-latest
      steps:
      - run: echo ${GITHUB_REF} ${GITHUB_HEAD_REF} ${GITHUB_BASE_REF} ${GITHUB_EVENT_PATH}
