on: 
  pull_request:
    branches:
      - main
    types: [closed]
name: merge main
jobs:
  firstJob:
      name: Echo GITHUB_HEAD_REF
      runs-on: ubuntu-latest
      steps:
        - name: get pr number
          run: echo $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        - name: echo GITHUB_HEAD_REF
          run: echo $GITHUB_HEAD_REF
  secoundJob:
    name: script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls -l
        run: |
          ls -l
        shell: bash
      - name: exec bash
        run: ./.github/workflows/create_tags.sh
        shell: bash
    
