on: 
  push:
    branches:
      - main
name: merge master
jobs:
  firstJob:
      name: Echo GITHUB_HEAD_REF
      runs-on: ubuntu-latest
      steps:
        - name: echo GITHUB_HEAD_REF
          run: echo $GITHUB_EVENT_PATH
        - name: set GITHUB_EVENT_PATH contents
          run: jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH" >> CONTENTS
        - name: echo CONTENTS
          run: echo $CONTENTS
        - name: echo GITHUB_EVENT_PATH
          run: echo $GITHUB_EVENT_PATH
