on: 
  push:
    branches:
      - main
name: merge master
jobs:
  firstJob:
      name: Echo GITHUB_HEAD_REF
      runs-on: ubuntu-latest
      steps:
      - run: echo ${GITHUB_REF} ${TEST} ${GITHUB_EVENT_NAME}
        env:
          TEST: hoge 
