on: 
  push:
    branches:
      - main
name: merge master
jobs:
  firstJob:
      name: Echo GITHUB_HEAD_REF
      runs-on: ubuntu-latest
      steps:
      - run: CONTENTS=$(jq --raw-output "$GITHUB_EVENT_PATH") | echo $(jq $CONTENTS)
