on: 
  pull_request:
    branches:
      - main
    types: [closed]
name: merge to main
jobs:
  setReleaseTag:
    name: script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: exec bash
        run: |
          chmod +x ./.github/workflows/create_tags.sh && \
          ./.github/workflows/create_tags.sh
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
