on:
  workflow_call:
jobs:
  OUTPUT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find changed files
        id: find-changed-files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.md

      - name: List all changed files markdown files
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
